import shuffleArray from "@/utils/shuffleArray";

enum Level {
  easy = 1,
  medium = 2,
  hard = 3,
} 
 
export interface Pazzle {
  id: number;
  video: string;
  task: string;
  level: Level;
  answer: string;
  youtube: string;
}

export const FOLDER = "tasks/";
 
 const DATA: Pazzle[] = [
   {
     id: 1,
     video: `0001.webm`,
     task: `0001.webp`,
     level: Level.easy,
     answer: "DJ SMASH - Волна",
     youtube: "https://youtu.be/-9t3N2UILtc?si=XpQzHLATIYT8MYBE",
   },
   {
     id: 2,
     video: "0002.WEBM",
     task: "0002.webp",
     level: Level.easy,
     answer: "Тима Беларусских - Мокрые Кроссы",
     youtube: "https://youtu.be/on5zXnvDoxk?si=DAg5I11PoeK9p8mk",
   },
   {
     id: 3,
     video: "0003.WEBM",
     task: "0003.webp",
     level: Level.easy,
     answer: "Dabro - На часах ноль-ноль",
     youtube: "https://youtu.be/RK4_D2D2KZs?si=2gU0GddZLrc28jLF",
   },
   {
     id: 4,
     video: "0004.webm",
     task: "0004.webp",
     level: Level.hard,
     answer: "Мирби - Танцы в труселях",
     youtube: "https://youtu.be/yjA6jFwxKOg?si=PEIp2XlIO75dvR5l",
   },
   {
     id: 5,
     video: "0005.webm",
     task: "0005.webp",
     level: Level.medium,
     answer: "HammAli & Navai - Птичка",
     youtube: "https://youtu.be/x105Z3X-NK0?si=WXtaIIEIa8hyj7aF",
   },
   {
     id: 6,
     video: "0006.webm",
     task: "0006.webp",
     level: Level.hard,
     answer: "Егор Крид - Сердцеедка",
     youtube: "https://youtu.be/6uHHWgJ6dsk?si=zZsXeyFbAqp9TFoB",
   },
   {
     id: 7,
     video: "0007.webm",
     task: "0007.webp",
     level: Level.medium,
     answer: "Артур Пирожков - Алкоголичка",
     youtube: "https://youtu.be/47JI4G-qYmc?si=t7ZKZX6uWypkgkjg",
   },
   {
     id: 8,
     video: "0008.webm",
     task: "0008.webp",
     level: Level.easy,
     answer: "Леонид Агутин – На сиреневой луне",
     youtube: "https://youtu.be/hSqAyOpBRUs?si=Y7lYuk_4xCYb9ymX",
   },
   {
     id: 9,
     video: "0009.webm",
     task: "0009.webp",
     level: Level.hard,
     answer: "Грибы - Тает Лёд",
     youtube: "https://youtu.be/Ptcp_xtQhbs?si=ss1CfzbRu7jlJCnB",
   },
   {
     id: 10,
     video: "0010.webm",
     task: "0010.webp",
     level: Level.easy,
     answer: "Ваня Дмитриенко - Венера-Юпитер",
     youtube: "https://youtu.be/u2XDNUHL_JM?si=XvI39JOq5VIgw2QG",
   },
   {
     id: 11,
     video: "0011.webm",
     task: "0011.webp",
     level: Level.easy,
     answer: "Валерий Меладзе - Салют, Вера",
     youtube: "https://youtu.be/y0o4j1qnO6Y?si=ELCz6zVq_Xa84bq9",
   },
   {
     id: 12,
     video: "0012.webm",
     task: "0012.webp",
     level: Level.medium,
     answer: "Amirchik - Либо люби",
     youtube: "https://youtu.be/zQjJyJc3b00?si=UiNYV_a_sxHLYOzr",
   },
   {
     id: 13,
     video: "0013.webm",
     task: "0013.webp",
     level: Level.medium,
     answer: "Клава Кока - Замуж",
     youtube: "https://youtu.be/ghHagXcMuv0?si=qqywUcxtL8P-pBq1",
   },
   {
     id: 14,
     video: "0014.webm",
     task: "0014.webp",
     level: Level.easy,
     answer: "Ленинград — WWW",
     youtube: "https://youtu.be/7w2ixHXhSDs?si=iRpGKYjwX6j8rqKQ",
   },
   {
     id: 15,
     video: "0015.webm",
     task: "0015.webp",
     level: Level.hard,
     answer: "А4 - Лама мама",
     youtube: "https://youtu.be/RrAXfYRII70?si=XQr3I6i2d1YVo7ql",
   },
   {
     id: 16,
     video: "0016.webm",
     task: "0016.webp",
     level: Level.medium,
     answer: "A.V.G - Я плачу",
     youtube: "https://youtu.be/aOLXZOc2iwk?si=hbKrD1s_iIXpAN80",
   },
   {
     id: 17,
     video: "0017.webm",
     task: "0017.webp",
     level: Level.medium,
     answer: "INSTASAMKA - За деньги - да",
     youtube: "https://youtu.be/rn-fGxWlnhM?si=mN8XjKXIds1_Bf65",
   },
   {
     id: 18,
     video: "0018.webm",
     task: "0018.webp",
     level: Level.medium,
     answer: "Тося Чайкина - В сердце бахнули стрелы",
     youtube: "https://youtu.be/kfQblFNnWts?si=Fyz0x9TLKBUDEBan",
   },
   {
     id: 19,
     video: "0019.webm",
     task: "0019.webp",
     level: Level.hard,
     answer: "Улька Пулька & Sivchik - Буратино",
     youtube: "https://youtu.be/_Wt6GttEOsg?si=rIcNQxDMdRf-3ho9",
   },
   {
     id: 20,
     video: "0020.webm",
     task: "0020.webp",
     level: Level.medium,
     answer: "SIVCHIK & Ангелина Волкова - Антошка",
     youtube: "https://youtu.be/prIebUiJfD8?si=evnoes60BxHZZkfy",
   },
   {
     id: 21,
     video: "0021.webm",
     task: "0021.webp",
     level: Level.medium,
     answer: "Лолита - На Титанике",
     youtube: "https://youtu.be/GsJPph70ytY?si=xDEJJijBWtobhCrE",
   },
   {
     id: 22,
     video: "0022.webm",
     task: "0022.webp",
     level: Level.easy,
     answer: "Серега - Черный бумер",
     youtube: "https://youtu.be/xCvD7Rf5i2I?si=rxR-Ldj_BzCAKkXb",
   },
   {
     id: 23,
     video: "0023.webm",
     task: "0023.webp",
     level: Level.easy,
     answer: "ХАБИБ & RADJO - Жёлтое такси",
     youtube: "https://youtu.be/yvQuv1uN4oE?si=8FoI9UAsBcK2dZl4",
   },
   {
     id: 24,
     video: "0024.webm",
     task: "0024.webp",
     level: Level.easy,
     answer: "Ольга Серябкина - Зеленоглазое такси",
     youtube: "https://youtu.be/qelXDh6TDy8?si=LoIgMsNnO7M43YZB",
   },
   {
     id: 25,
     video: "0025.webm",
     task: "0025.webp",
     level: Level.medium,
     answer: "MACAN - ASPHALT 8",
     youtube: "https://youtu.be/RuI96FlFU54?si=3q_UF2mbxlLBdVQa",
   },
   {
     id: 26,
     video: "0026.webm",
     task: "0026.webp",
     level: Level.medium,
     answer: "Татьяна Куртукова - Матушка",
     youtube: "https://youtu.be/AFcIXxkFxK4?si=2F_dxeG6DC4dBPJ1",
   },
   {
     id: 27,
     video: "0027.webm",
     task: "0027.webp",
     level: Level.medium,
     answer: "Jazzdauren - Дарите женщинам цветы",
     youtube: "https://youtu.be/bdGOGqkN6Po?si=uj2QyHUl5PTUu2tY",
   },
   {
     id: 28,
     video: "0028.webm",
     task: "0028.webp",
     level: Level.hard,
     answer: "Люся Чеботина - за бывшего",
     youtube: "https://youtu.be/6BZBVa1McXE?si=Ere4D3Do2MzxKDX-",
   },
   {
     id: 29,
     video: "0029.webm",
     task: "0029.webp",
     level: Level.easy,
     answer: "Gayazov$ Brother$ — Малиновая лада",
     youtube: "https://youtu.be/TvEkldfa3T0?si=LuhNtm8s1dbI0keV",
   },
   {
     id: 30,
     video: "0030.webm",
     task: "0030.webp",
     level: Level.hard,
     answer: "Хабиб - Ягода малинка",
     youtube: "https://youtu.be/Rt2zZSaOFtw?si=4-6dY3jvTZwh3FX0",
   },
   {
     id: 31,
     video: "0031.webm",
     task: "0031.webp",
     level: Level.hard,
     answer: "Jakone, Kiliana - Асфальт",
     youtube: "https://youtu.be/1ll3FvVk6BA?si=g2hEjnkYxGYoF8An",
   },
   {
     id: 32,
     video: "0032.webm",
     task: "0032.webp",
     level: Level.medium,
     answer: "DEAD BLONDE – Мальчик на девятке",
     youtube: "https://youtu.be/JtcrAcBB3Ps?si=eKmTO_g0SWid2Zhj",
   },
   {
     id: 33,
     video: "0033.webm",
     task: "0033.webp",
     level: Level.easy,
     answer: "Весёлые Ребята - Розовые розы",
     youtube: "https://youtu.be/ghqlY7OnjC8?si=91aAsTUxCBkRM5oU",
   },
   {
     id: 34,
     video: "0034.webm",
     task: "0034.webp",
     level: Level.easy,
     answer: "Юрий Шатунов - Белые Розы",
     youtube: "https://youtu.be/BF0CmXdxV6U?si=a-iYApcQgDmT3NSI",
   },
   {
     id: 35,
     video: "0035.webm",
     task: "0035.webp",
     level: Level.medium,
     answer: "Люся Чеботина - Солнце Монако",
     youtube: "https://youtu.be/sfd2xj9xtN0?si=dNORE96fOiLYE744",
   },
   {
     id: 36,
     video: "0036.webm",
     task: "0036.webp",
     level: Level.medium,
     answer: "Натали - Ветер с моря дул",
     youtube: "https://youtu.be/ngsWYx0XN2I?si=Q4zaWbtTTQqsmpOt",
   },
   {
     id: 37,
     video: "0037.webm",
     task: "0037.webp",
     level: Level.medium,
     answer: "Мираж - Музыка нас связала",
     youtube: "https://youtu.be/GjOvzWJbFdA?si=96o2YksmbeouZPFf",
   },
   {
     id: 38,
     video: "0038.webm",
     task: "0038.webp",
     level: Level.medium,
     answer: "Андрей Губин - Зима - холода",
     youtube: "https://youtu.be/Q-nuDx6iUpo?si=Ps7ptEHi7NDIQfw2",
   },
   {
     id: 39,
     video: "0039.webm",
     task: "0039.webp",
     level: Level.medium,
     answer: "ДДТ - Что такое осень",
     youtube: "https://youtu.be/5KC-iscJtsI?si=UEFLqeqSLfReOKTc",
   },
   {
     id: 40,
     video: "0040.webm",
     task: "0040.webp",
     level: Level.hard,
     answer: "Татьяна Буланова - Ясный мой свет",
     youtube: "https://youtu.be/R8r8BX57RNM?si=PvEZnjL2cAfkQMiW",
   },
   {
     id: 41,
     video: "0041.webm",
     task: "0041.webp",
     level: Level.hard,
     answer: "JONY - Комета",
     youtube: "https://youtu.be/FXdpkDlAF0M?si=uaFPoIOdEvBaojdH",
   },
   {
     id: 42,
     video: "0042.webm",
     task: "0042.webp",
     level: Level.medium,
     answer: "Егор Крид feat. Михаил Шуфутинский - 3-е Сентября",
     youtube: "https://youtu.be/HUCPwzmF7hA?si=vfb1k6lYdVcbQ65u",
   },
   {
     id: 43,
     video: "0043.webm",
     task: "0043.webp",
     level: Level.medium,
     answer: "Евгений Осин - Плачет девушка...",
     youtube: "https://youtu.be/BFfPKzoQlpo?si=IcIIe6CZ6XF2mVUE",
   },
   {
     id: 44,
     video: "0044.webm",
     task: "0044.webp",
     level: Level.medium,
     answer: "Тимати - Плачут небеса",
     youtube: "https://www.youtube.com/watch?v=exj8AaoBVSY",
   },
   {
     id: 45,
     video: "0045.webm",
     task: "0045.webp",
     level: Level.medium,
     answer: "Алёна Апина - электричка",
     youtube: "https://youtu.be/xSTSq8_Wp_Y?si=-gaG1k4qFxe83eLf",
   },
   {
     id: 46,
     video: "0046.webm",
     task: "0046.webp",
     level: Level.hard,
     answer: "Ирина Аллегрова Младший лейтенант",
     youtube: "https://youtu.be/CPRTVCL9OOI?si=h2r2EYyXlnKHgFCt",
   },
   {
     id: 47,
     video: "0047.webm",
     task: "0047.webp",
     level: Level.medium,
     answer: "Ольга Бузова - Мало половин",
     youtube: "https://youtu.be/Ro6GHxFj8uk?si=PWeu-SbNG7ZaXnUV",
   },
   {
     id: 48,
     video: "0048.webm",
     task: "0048.webp",
     level: Level.easy,
     answer: "Линда - Мало Огня",
     youtube: "https://youtu.be/IwAuCdO62UU?si=NlkKpO1BO8tDcEN5",
   },
   {
     id: 49,
     video: "0049.webm",
     task: "0049.webp",
     level: Level.hard,
     answer: "Форум - Белая ночь",
     youtube: "https://youtu.be/Jm-7DODaTvU?si=zv9S3wNttiRv-4ao",
   },
   {
     id: 50,
     video: "0050.webm",
     task: "0050.webp",
     level: Level.hard,
     answer: "Юрий Шатунов - Розовый вечер",
     youtube: "https://youtu.be/IZjjd41Y6pU?si=FxBm8krfqSCbdobL",
   },
   {
     id: 51,
     video: "0051.webm",
     task: "0051.webp",
     level: Level.medium,
     answer: "CarMan - Лондон, гуд бай",
     youtube: "https://youtu.be/ylpNEb31k4U?si=9l50VpXNpmponbjN",
   },
   {
     id: 52,
     video: "0052.webm",
     task: "0052.webp",
     level: Level.medium,
     answer: "Вирус - Ты меня не ищи",
     youtube: "https://youtu.be/UHjLoLhwqFE?si=RrqCq6S6wQHtaGJo",
   },
   {
     id: 53,
     video: "0053.webm",
     task: "0053.webp",
     level: Level.medium,
     answer: "Александр Серов - Я люблю тебя до слёз",
     youtube: "https://youtu.be/ywXNn3hoPX4?si=F_nHTuYrbL3I4dD0",
   },
   {
     id: 54,
     video: "0054.webm",
     task: "0054.webp",
     level: Level.easy,
     answer: "Анжелика Варум - Зимняя вишня",
     youtube: "https://youtu.be/QG6VBkokjSY?si=Vy9eVczaTdqghu-g",
   },
   {
     id: 55,
     video: "0055.webm",
     task: "0055.webp",
     level: Level.hard,
     answer: "Борис Моисеев и Николай Трубач - Голубая луна",
     youtube: "https://youtu.be/53tZxpfmQwg?si=Smjy6bg4pQ93QQtK",
   },
   {
     id: 56,
     video: "0056.webm",
     task: "0056.webp",
     level: Level.hard,
     answer: "Владимир Маркин - я готов целовать песок",
     youtube: "https://youtu.be/5MGEQs3-7Yc?si=POygUnTPDNjWl3tA",
   },
   {
     id: 57,
     video: "0057.webm",
     task: "0057.webp",
     level: Level.hard,
     answer: "Мираж - Новый герой",
     youtube: "https://youtu.be/VI59CbJ2EcQ?si=aLyVB5AkNC9B8AWi",
   },
   {
     id: 58,
     video: "0058.webm",
     task: "0058.webp",
     level: Level.hard,
     answer: "Anna Asti - По барам",
     youtube: "https://youtu.be/Cf2ASJCa_Iw?si=y-0BgUPccjOwNksj",
   },
   {
     id: 59,
     video: "0059.webm",
     task: "0059.webp",
     level: Level.medium,
     answer: "Anna Asti - Ночью на кухне",
     youtube: "https://youtu.be/h7y_0Q9Nd4w?si=AfR05niZB8w9GAAz",
   },
   {
     id: 60,
     video: "0060.webm",
     task: "0060.webp",
     level: Level.medium,
     answer: "Джарахов & Markul – Я в моменте",
     youtube: "https://youtu.be/nQO5OQbDffc?si=fL-C6aOn9AST7yaa",
   },
   {
     id: 61,
     video: "0061.webm",
     task: "0061.webp",
     level: Level.medium,
     answer: "#2Маши - мама, я танцую",
     youtube: "https://youtu.be/jezU0MUixaY?si=mfh2-Ze7tgiOW4NY",
   },
   {
     id: 62,
     video: "0062.webm",
     task: "0062.webp",
     level: Level.medium,
     answer: "Руки Вверх! - 18 мне уже",
     youtube: "https://youtu.be/Hxab_Sr132o?si=P4cY0UcyDQz6DxSe",
   },
   {
     id: 63,
     video: "0063.webm",
     task: "0063.webp",
     level: Level.medium,
     answer: "Блестящие - За четыре моря",
     youtube: "https://youtu.be/54UspYYEaVs?si=jPAxzloh4vIG8DXP",
   },
   {
     id: 64,
     video: "0064.webm",
     task: "0064.webp",
     level: Level.medium,
     answer: "Баста - На заре",
     youtube: "https://youtu.be/5kfPCxXZPdA?si=_1DZ8TdUPRNdgYFn",
   },
   {
     id: 65,
     video: "0065.webm",
     task: "0065.webp",
     level: Level.hard,
     answer: "Artik & Asti - Гармония",
     youtube: "https://youtu.be/I7-Djz-CBOY?si=eaphu8dGXgcy4MP-",
   },
   {
     id: 66,
     video: "0066.webm",
     task: "0066.webp",
     level: Level.medium,
     answer: "Валерий Кипелов - Я свободен",
     youtube: "https://youtu.be/QXDRPtufEbA?si=lN8rt9KDwg-aChbj",
   },
   {
     id: 67,
     video: "0067.webm",
     task: "0067.webp",
     level: Level.medium,
     answer: "Жуки - Батарейка",
     youtube: "https://youtu.be/UYqQSCnIecE?si=lztlPgvrL3huis4b",
   },
   {
     id: 68,
     video: "0068.webm",
     task: "0068.webp",
     level: Level.medium,
     answer: "Hi-Fi - Седьмой лепесток",
     youtube: "https://youtu.be/HIJdIHouajY?si=unyTWQTIlNKQcsv9",
   },
   {
     id: 69,
     video: "0069.webm",
     task: "0069.webp",
     level: Level.medium,
     answer: "Бумбокс - Вахтерам",
     youtube: "https://youtu.be/tnZPDs9qepA?si=BTVxm_-qRFKsHwM7",
   },
   {
     id: 70,
     video: "0070.webm",
     task: "0070.webp",
     level: Level.hard,
     answer: "Султан Лагучев - Горький вкус",
     youtube: "https://youtu.be/Bx8Fo7WRpXg?si=i1-SSF65_BvAGYJo",
   },
   {
     id: 71,
     video: "0071.webm",
     task: "0071.webp",
     level: Level.medium,
     answer: "Ленинград — Дорожная",
     youtube: "https://youtu.be/VVkwoY6dQFo?si=tiGNCAlj2iQykSah",
   },
   {
     id: 72,
     video: "0072.webm",
     task: "0072.webp",
     level: Level.hard,
     answer: "Андрей Губин - Ночь",
     youtube: "https://youtu.be/cVS3EAJpNPY?si=hPL4oFO-flvBR-78",
   },
   {
     id: 73,
     video: "0073.webm",
     task: "0073.webp",
     level: Level.medium,
     answer: "Тима Белорусских - Витаминка",
     youtube: "https://youtu.be/zn0XeYg0hIs?si=1S7PZFeSQMejiB2W",
   },
   {
     id: 74,
     video: "0074.webm",
     task: "0074.webp",
     level: Level.medium,
     answer: "Ольга Бузова - Танцуй под Бузову",
     youtube: "https://youtu.be/uH6WXHbBbB4?si=Rlv2yG7wFjki3Oc-",
   },
 ];

DATA.forEach(el => {
  el.video = `${FOLDER}${el.video}`
  el.task = `${FOLDER}${el.task}`;
})

export default class ApiHelper {
  static getTask(id: number): Pazzle {
    const result = DATA.find(el => el.id === id);

    if (result !== undefined) {
      return result;
    } else {
      throw new Error(`задание с id ${id} не существует`);
    }
  }

  static getShakeTasksID (): Pazzle["id"][] {
    const ids = Array.from({ length: DATA.length }, (_, i) => i + 1);
    return shuffleArray(ids);
  }
}


